carthage update RxSwift --platform ios --no-use-binaries --cache-builds
carthage update SnapKit --platform ios --no-use-binaries --cache-builds
carthage update Material --platform ios --no-use-binaries --cache-builds
carthage update RxHttpClient --platform ios --no-use-binaries --cache-builds
carthage update RxDataFlow --platform ios --no-use-binaries --cache-builds
carthage update RxDataSources --platform ios --no-use-binaries --cache-builds
carthage update Unbox --platform ios --no-use-binaries --cache-builds
carthage update Wrap --platform ios --no-use-binaries --cache-builds
carthage update RxGesture --platform ios --no-use-binaries --cache-builds
carthage update OneSignal-iOS-SDK --platform ios --no-use-binaries --cache-builds
carthage update Auth0.swift --platform ios --no-use-binaries --cache-builds
carthage update JWTDecode.swift --platform ios --no-use-binaries --cache-builds
carthage update realm-cocoa --platform ios --no-use-binaries --cache-builds
